apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: postgres-config
    literals:
      - postgresdb=nijatdatabase
      - postgresuser=nijat
  - name: pgadmin-config
    literals:
      - pgadmin-mail=nijat@nijat.com