apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mysql
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          exec:
            command:
            - sh
            - -c 
            - mysqladmin ping -h127.0.0.1 -u root -p$(MYSQL_ROOT_PASSWORD)
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

