apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - hpa-high.yaml

replacements:
  - source:
      kind: Deployment
      name: mysql
      fieldPath: metadata.name
    targets:
      - select:
          kind: HorizontalPodAutoscaler
          name: mysql-hpa
        fieldPaths:
          - spec.scaleTargetRef.name

  - source:
      kind: Deployment
      name: postgres
      fieldPath: metadata.name
    targets:
      - select:
          kind: HorizontalPodAutoscaler
          name: postgres-hpa
        fieldPaths:
          - spec.scaleTargetRef.name
