apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress-adminer.yaml
  - ingress-pgadmin.yaml

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: adminer-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: "/adminer"