apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/cron
  - ../../components/pvc
  - ../../components/ingress
  - ../../components/svc
  - ../../components/adminer
  - ../../components/resources/high
  - ../../components/hpa/hpa-medium
  - ../../components/probes/liveness
  - ../../components/probes/readiness
  - ../../components/probes/startup
  - ../../components/secrets
  - ../../components/configmap

namePrefix: "test-"